version: '3'
services:
  sumo-simulation:
    build: .
    volumes:
      - ../sumo-scenarios:/sumo-data
    environment:
      - PORT=8080
      - SUMO_CONF_FILE=/sumo-data/run.sumocfg
    ports:
        - "8080:8080"